title: Delsi Sierra
logo: https://github.com/Delsiwels/delsi.github.io/commit/9679fea34cf7a9122e2aac6554277f9e82f27207#commitcomment-138416960
#description:text below image
show_downloads: true
theme: jekyll-theme-minimal
