title: Delsi Sierra
logo: https://github.com/Delsiwels/delsi.github.io/blob/68731192ba739ac3766f3a948f4b5267773f0a36/pic.jpg
#description:text below image
show_downloads: true
theme: jekyll-theme-minimal
