title: Delsi Sierra
logo: ![1517585034745](https://github.com/Delsiwels/delsi.github.io/assets/32222626/7efcf920-20e6-4345-ab06-8c2e980555c7)
#description:text below image
show_downloads: true
theme: jekyll-theme-minimal
